---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: movie-voting
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/data/movie-voting-postgres/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  selector:
    matchLabels:
      app: movie-voting

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-voting-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-voting
      type: db
  template:
    metadata:
      name: movie-voting-postgres
      labels:
        app: movie-voting
        type: db
      annotations:
          prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: postgres
          image: postgres:11.2-alpine
          readinessProbe:
            tcpSocket:
              port: 5432
          env:
          - name: POSTGRES_DB
            value: movie
          - name: POSTGRES_USER
            value: ${POSTGRES_USER}
          - name: POSTGRES_PASSWORD
            value: ${POSTGRES_PASSWORD}
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pvc
        - name: postgres-exporter
          image: wrouesnel/postgres_exporter:latest
          ports:
            - name: pg-metrics
              containerPort: 9187
          env:
          - name: POSTGRES_DB
            value: movie
          - name: DATA_SOURCE_URI
            value: "127.0.0.1:5432/$(POSTGRES_DB)?sslmode=disable"
          - name: DATA_SOURCE_USER
            value: ${POSTGRES_USER}
          - name: DATA_SOURCE_PASS
            value: ${POSTGRES_PASSWORD}
          - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
            value: "true"
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc

---
  apiVersion: v1
  kind: Service
  metadata:
    name: postgres-service
  spec:
    type: ClusterIP
    selector:
      app: movie-voting
      type: db
    ports:
      - targetPort: 5432
        port: 5432
